version: '3.8'

services:
  server:
    restart: always
    build:
      context: ./server
    ports:
      - "8004:8000"
    depends_on:
      - mongodb

  # frontend:
  #   restart: always
  #   build: ./frontend
  #   ports:
  #     - "5173:5173"
  # # frontend:
  # #    build:
  # #      context: .
  # #      dockerfile: frontend/Dockerfile
  # #    volumes:
  # #      - ./:/frontend:delegated
  # #      - /node_modules
  # #    ports:
  # #      - 5173:5173
  # #    environment:
  # #     - WDS_SOCKET_HOST=127.0.0.1 
  # #     - CHOKIDAR_USEPOLLING=true
  # #     - WATCHPACK_POLLING=true 
  # #    command: npm run dev
  frontend:
    build: ./frontend
    environment:
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    volumes: 
      - ./frontend:/var/app/
      - /var/app/node_modules
    ports:
      - 5173:5173

  mongodb:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
